config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :courses, only: [:index] do
    resources :lessons, only: [:index] do
      resources :sections, only: [:index]
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :user_section_statuses, only: [:update], param: :section_id
  end

  # Admin
  namespace :admin do
    root 'dashboard#index'
    post '/send-notify', to: 'daily_notifications#send_daily_activities_email'
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sections
    end
    resources :users do
      resources :user_courses, only: [:index, :new, :create, :destroy]
      member do
        put 'set_role', to: 'users#set_role'
        get 'lessons/:course_id', to: 'user_courses#lessons', as: :lessons
        get 'lessons/:course_id/sections/:lesson_id', to: 'user_courses#sections', as: :sections
      end
    end
  end
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :sections, dependent: :destroy
  accepts_nested_attributes_for :sections, reject_if: :all_blank, allow_destroy: true

  validates :name, presence: true
  validates :description, presence: true
  validates :course_id, presence: true
  validate :course_id_exists

  private
    def course_id_exists
      errors.add(:course_id, "must exist") unless Course.exists?(course_id)
    end

    def self.ransackable_attributes(*)
      %w[name]
    end
end

app/controllers/admin/lessons_controller.rb
class Admin::LessonsController < Admin::BaseController
  def index
  end

  def show
  end

  def new
    @lesson = Lesson.new
    @courses = Course.all
    @lesson.sections.build
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      @courses = Course.find_by(id: @lesson.course_id)
      redirect_to admin_course_path(@courses)
    else
      @courses = Course.all
      render 'new'
    end
  end

  def edit
    @lesson = Lesson.find_by(id: params[:id])
    return unless valid_resource?(@lesson)
    @courses = Course.all
  end

  def update
    @lesson = Lesson.find_by(id: params[:id])
    return unless valid_resource?(@lesson)

    if !@lesson.nil? && @lesson.update(lesson_params)
      @course = Course.find_by(id: @lesson.course_id)
      redirect_to admin_course_path(@course), notice: 'Lesson was successfully updated.'
    else
      @courses = Course.all
      render 'edit'
    end
  end

  def destroy
    @lesson = Lesson.find_by(id: params[:id])
    return unless valid_resource?(@lesson)

    @lesson.destroy
    flash[:success] = "Lesson deleted"
    redirect_back(fallback_location: root_path)
  end

  private
    def lesson_params
      params.require(:lesson).permit(:name, :description, :course_id, sections_attributes: [:id, :name, :question, :answer, :_destroy])
    end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :logged_in_user

  def index
    @user_courses = UserCourse.where(user_id: current_user.id, course_id: params[:course_id])
    return unless valid_resource?(@user_courses)

    @course = Course.find_by(id: params[:course_id])
    return unless valid_resource?(@course)

    @lessons_search = @course.lessons.ransack(name_cont: params[:search])
    @lessons = @lessons_search.result.paginate(page: params[:page], per_page: 3)

    @lessons_with_completion = {}
    @lessons.each do |lesson|
      sections = lesson.sections
                       .joins("LEFT JOIN user_section_statuses ON user_section_statuses.section_id = sections.id AND user_section_statuses.user_id = #{current_user.id}")
                       .select("sections.*, COALESCE(user_section_statuses.status, 0) AS status")

      total_sections = sections.length
      count_complete = sections.count { |section| section.status == 1 }
      completion_percentage = total_sections.zero? ? 0 : (count_complete.to_f / total_sections) * 100
      @lessons_with_completion[lesson.id] = completion_percentage
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/index.html.erb
<% provide(:title, 'Course / ' + @course.name) %>

<div class="card">
  <div class="card-header col-12">
    <h1 class="card-title lessons-title"><%= @course.name %> - Lessons</h1>
  </div>
  <!-- /.card-header -->
  <div class="card-body">
    <table class="table table-bordered">
      <thead>
      <tr>
        <th style="width: 10px">#</th>
        <th>Task</th>
        <th>Progress</th>
        <th style="width: 40px">Label</th>
        <th style="width: 100px"></th>
      </tr>
      </thead>
      <tbody>
      <%
        progress_color = {
          25 => 'bg-danger',
          50 => 'bg-warning',
          75 => 'bg-primary',
          100 => 'bg-success'
        }
        order_number = 0
        if @lessons.present? && @lessons.any?
          @lessons.each do |lesson|
            progress = @lessons_with_completion[lesson.id]

            selected_color = nil
            progress_color.each do |key, color|
              if progress < key
                selected_color = color
                break
              end
            end
      %>

          <tr>
            <td><%= order_number+= 1 %></td>
            <td>
              <%= lesson.name %>
            </td>
            <td>
              <div class="progress progress-xs">
                <div class="progress-bar <%= selected_color %>" style="width: <%= progress %>%"></div>
              </div>
            </td>
            <td><span class="badge <%= selected_color %>"><%= progress %>%</span></td>
            <td style="text-align: center;">
              <%= link_to course_lesson_sections_path(course_id: @course.id, lesson_id: lesson.id) do %>
                <% if progress != 100
                     "Start"
                   else
                     "View"
                   end
                %>
              <% end %>
            </td>
          </tr>
        <% end %>

      <% end %>
      </tbody>
    </table>

  </div>
  <!-- /.card-body -->
  <div class="card-footer d-flex justify-content-end">
    <%= paginate @lessons %>
  </div>
  <!-- /.card -->
</div>