config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :courses, only: [:index] do
    resources :lessons, only: [:index] do
      resources :sections, only: [:index]
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :user_section_statuses, only: [:update], param: :section_id
  end

  # Admin
  namespace :admin do
    root 'dashboard#index'
    post '/send-notify', to: 'daily_notifications#send_daily_activities_email'
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sections
    end
    resources :users do
      resources :user_courses, only: [:index, :new, :create, :destroy]
      member do
        put 'set_role', to: 'users#set_role'
        get 'lessons/:course_id', to: 'user_courses#lessons', as: :lessons
        get 'lessons/:course_id/sections/:lesson_id', to: 'user_courses#sections', as: :sections
      end
    end
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private
    def require_admin
      unless current_user
        store_location_for(:user, request.fullpath) if request.get?
        redirect_to new_user_session_path
        return
      end

      stored_location = stored_location_for(current_user)
      redirect_to stored_location || root_path, alert: 'Access denied.' unless current_user.is_admin?
    end
end

app/helpers/admin/base_helper.rb
module Admin::BaseHelper
end

app/views/admin/base/_application.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'adminlte/dist/css/adminlte.css' %>
  <%= render 'layouts/rails_default' %>
  <%= render 'layouts/shim' %>
  <%= javascript_importmap_tags %>
  <%= favicon_link_tag 'mor.png' %>
</head>

<body class="body-admin">
  <div class="wrapper">
    <%= render 'admin/base/header' %>
    <%= render 'admin/base/sidebar' %>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
      </div>
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2 m-1">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><%= link_to "Home", admin_root_path %></li>
                <li class="breadcrumb-item active"><%= yield(:title) %></li>
              </ol>
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Main content -->
      <div class="content">
        <div class="container-fluid">
          <%= yield %>
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

    <%= render 'admin/base/footer' %>
    <%= render 'admin/base/control_sidebar' %>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'plugins/jquery/jquery.min', 'plugins/bootstrap/js/bootstrap.bundle.min', 'dist/js/adminlte.min' %>
</body>

<script>
    function confirmDelete(event) {
        var confirmMessage = confirm("Are you sure?");
        if (!confirmMessage) {
            event.preventDefault(); // Ngăn chặn sự kiện mặc định (ví dụ: không chuyển hướng)
        }
    }
</script>

app/views/admin/base/_control_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <h5>Title</h5>
    <p>Sidebar content</p>
  </div>
</aside>
<!-- /.control-sidebar -->

app/views/admin/base/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>
<!-- Main Footer -->

app/views/admin/base/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <%= link_to "Home", admin_root_path, class: "nav-link" %>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Navbar Search -->
    <li class="nav-item">
      <a class="nav-link" data-widget="navbar-search" href="#" role="button">
        <i class="fas fa-search"></i>
      </a>
      <div class="navbar-search-block">
        <form class="form-inline">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
              <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                <i class="fas fa-times"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="/assets/adminlte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="/assets/adminlte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="/assets/adminlte/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="fullscreen" href="#" role="button">
        <i class="fas fa-expand-arrows-alt"></i>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
        <i class="fas fa-th-large"></i>
      </a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/admin/base/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Logo -->
  <%= link_to root_path, class: "brand-link sidebar-user-info" do %>
    <%= image_tag("/assets/adminlte/dist/img/AdminLTELogo.png", alt: "AdminLTE Logo", class: "brand-image img-circle elevation-3 sidebar-avatar", style: "opacity: .8") %>
    <span class="brand-text font-weight-light sidebar-name"><b>RAILS DEMO</b></span>
  <% end %>

  <!-- Sidebar -->
  <div class="sidebar sidebar-admin">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="/assets/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <span class="d-block username">
          <%= current_user.name %>
        </span>
      </div>
    </div>

    <!-- SidebarSearch Form -->
    <input id="sidebar-search-input" class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to(admin_users_path, class: "nav-link", data: { turbo: false}) do %>
            <i class="nav-icon 	fas fa-id-card"></i>
            <p>Users</p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to(admin_courses_path, class: "nav-link", data: { turbo: false}) do %>
            <i class="nav-icon fas fa-th"></i>
            <p>Courses
              <span class="right badge badge-danger">New</span>
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

<script>
    const searchInput = document.getElementById('sidebar-search-input');
    searchInput.addEventListener('keypress', function(event) {
        if (event.key === 'Enter') {
            performSearch();
        }
    });

    function performSearch() {
        let searchTerm = searchInput.value;
        event.preventDefault();

        let search = searchTerm.trim();
        let currentPath = window.location.pathname;
        window.location.href = `${currentPath}?search=${encodeURIComponent(search)}`;
    }

    document.addEventListener("DOMContentLoaded", function() {
        const searchValue = new URLSearchParams(window.location.search).get("search");

        if (searchInput && searchValue !== null) {
            searchInput.value = decodeURIComponent(searchValue);
        }
    });
</script>