config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
  }

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/news', to: 'static_pages#news'

  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :courses, only: [:index] do
    resources :lessons, only: [:index] do
      resources :sections, only: [:index]
    end
  end
  resources :users do
    member do
      get :following, :followers
    end
    resources :user_section_statuses, only: [:update], param: :section_id
  end

  # Admin
  namespace :admin do
    root 'dashboard#index'
    post '/send-notify', to: 'daily_notifications#send_daily_activities_email'
    resources :dashboard, only: [:index]
    resources :courses
    resources :lessons do
      resources :sections
    end
    resources :users do
      resources :user_courses, only: [:index, :new, :create, :destroy]
      member do
        put 'set_role', to: 'users#set_role'
        get 'lessons/:course_id', to: 'user_courses#lessons', as: :lessons
        get 'lessons/:course_id/sections/:lesson_id', to: 'user_courses#sections', as: :sections
      end
    end
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < Admin::BaseController
  def index
    @courses_search = Course.ransack(name_cont: params[:search])
    @courses = @courses_search.result.paginate(page: params[:page], per_page: 10)
  end

  def show
    @course = Course.find_by(id: params[:id])
    return unless valid_resource?(@course)
    @lessons_search = @course.lessons.ransack(name_cont: params[:search])
    @lessons = @lessons_search.result.paginate(page: params[:page], per_page: 5)
  end

  def new
    @course = Course.new
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :logged_in_user

  def index
    @user_courses = UserCourse.where(user_id: current_user.id)
    @courses_search = Course.joins(:user_courses).where(user_courses: { id: @user_courses.map(&:id) }).ransack(name_cont: params[:search])
    @courses = @courses_search.result.paginate(page: params[:page], per_page: 6)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/index.html.erb
<% provide(:title, 'Courses') %>

<h1>Courses</h1>
<% if @courses.present? %>
  <% @courses.each_slice(3) do |course_group| %>
    <div class="row">
      <% course_group.each do |course| %>
        <div class="col-md-4">
          <% @colors = %w[bg-info bg-warning bg-success] unless @colors.present? %>
          <% @current_color_index ||= 0 %>
          <% @current_color = @colors[@current_color_index] %>
          <% @current_color_index = (@current_color_index + 1) % @colors.length %>
          <%= link_to course_lessons_path(course_id: course.id), class: "no-underline" do %>
            <div class="relative overflow-hidden">
              <%= image_tag('courses/' + course.image, class: "object-cover rounded-t-lg w-full h-full course-image", alt: course.name) %>
            </div>
            <div class="info-box <%= @current_color %>" style="display: flex; padding: 10px 10px">
              <span class="info-box-icon"><i class="fas fa-book-open"></i></span>
              <div class="info-box-content" style="margin: 0 5px">
                <span class="info-box-text" style="color: black"><%= course.name %></span>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>